let tvdata=[
        {
          "Sr.No": 1,
          "title": "Breaking Bad",
          "Ratings": 9.5,
          "thumbnail":"https://i.pinimg.com/564x/df/2b/d9/df2bd9f5143e28f6e417e437bdcd7bc3.jpg",
          "Duration (in Min)": 49,
          "Votes": 1819514,
          "year": 2008,
          "genres": "Crime",
          "Summary": "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future."
        },
        {
          "Sr.No": 2,
          "title": "Game of Thrones",
          "Ratings": 9.2,
          "Duration (in Min)": 57,
          "thumbnail":"https://i.pinimg.com/564x/69/00/26/690026226e7e7f3ac52a04d2f8c15ac0.jpg",
          "Votes": 2044330,
          "year": 2011,
          "genres": "Action",
          "Summary": "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia."
        },
        {
          "Sr.No": 3,
          "title": "Mirzapur",
          "Ratings": 8.5,
          "Duration (in Min)": 60,
          "thumbnail":"https://i.pinimg.com/564x/77/a0/95/77a095f42ec8f99efe0a63c72ae31027.jpg",
          "Votes": 70705,
          "year": 2018,
          "genres": "Action",
          "Summary": "A shocking incident at a wedding procession ignites a series of events entangling the lives of two families in the lawless city of Mirzapur."
        },
        {
          "Sr.No": 4,
          "title": "The Boys",
          "Ratings": 8.7,
          "Duration (in Min)": 60,
          "thumbnail":"https://i.pinimg.com/236x/41/d8/dc/41d8dcb0e51d58bc62bc5b92a7767d6f.jpg",
          "Votes": 462292,
          "year": 2019,
          "genres": "Action",
          "Summary": "A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers."
        },
        {
          "Sr.No": 5,
          "title": "Daredevil",
          "Ratings": 8.6,
          "Duration (in Min)": 54,
          "thumbnail":"https://i.pinimg.com/564x/e3/95/a6/e395a6346aeb90ea908415733cb973d2.jpg",
          "Votes": 432354,
          "year": 2015,
          "genres": "Action",
          "Summary": "A blind lawyer by day, vigilante by night. Matt Murdock fights the crime of New York as Daredevil."
        },
        {
          "Sr.No": 6,
          "title": "The Walking Dead",
          "Ratings": 8.1,
          "Duration (in Min)": 44,
          "thumbnail":"https://i.pinimg.com/736x/33/27/cd/3327cd760f8506e801d02579e9ff8962.jpg",
          "Votes": 966812,
          "year": 2010,
          "genres": "Drama",
          "Summary": "Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins and must lead a group of survivors to stay alive."
        },
        {
          "Sr.No": 7,
          "title": "Sacred Games",
          "Ratings": 8.5,
          "Duration (in Min)": 50,
          "thumbnail":"https://i.pinimg.com/564x/7f/6d/ca/7f6dca071b1d01c7bfd58a25b3454c65.jpg",
          "Votes": 87113,
          "year": 2018,
          "genres": "Action",
          "Summary": "A link in their pasts leads an honest cop to a fugitive gang boss, whose cryptic warning spurs the officer on a quest to save Mumbai from cataclysm."
        },
        {
          "Sr.No": 8,
          "title": "Nacros",
          "Ratings": 8.5,
          "Duration (in Min)": 27,
          "thumbnail":"https://i.pinimg.com/564x/18/c4/29/18c4298439adef9eddbc491f7ffb3d82.jpg",
          "Votes": 3127,
          "year": 2018,
          "genres": "Crime",
          "Summary": "A suicidal man and a deadly assassin encounter the world of immortality in this black comedy suspense thriller."
        },
        {
          "Sr.No": 9,
          "title": "Breathe",
          "Ratings": 8.3,
          "Duration (in Min)": 45,
          "thumbnail":"https://i.pinimg.com/736x/66/5c/48/665c48cb3cf102024741ed2e41e9f856.jpg",
          "Votes": 19886,
          "year": 2018,
          "genres": "Crime",
          "Summary": "This series just asks one question - how far will you go to protect the one you love. Two desperate and driven men must engage in the ultimate cat and mouse game to save the one they love."
        },
        {
          "Sr.No": 10,
          "title": "The Family Man",
          "Ratings": 8.7,
          "Duration (in Min)": 45,
          "thumbnail":"https://i.pinimg.com/736x/6b/92/98/6b9298dfb22de292d220331e3c795a99.jpg",
          "Votes": 85465,
          "year": 2019,
          "genres": "Action",
          "Summary": "A working man from the National Investigation Agency tries to protect the nation from terrorism, but he also needs to keep his family safe from his secret job."
        },
        {
          "Sr.No": 11,
          "title": "Chernobyl",
          "Ratings": 9.4,
          "Duration (in Min)": 330,
          "thumbnail":"https://i.pinimg.com/736x/b6/86/c3/b686c3eaf702e60e756a1f25c5a617a3.jpg",
          "Votes": 730169,
          "year": 2019,
          "genres": "Drama",
          "Summary": "In April 1986, an explosion at the Chernobyl nuclear power plant in the Union of Soviet Socialist Republics becomes one of the world's worst man-made catastrophes."
        },
        {
          "Sr.No": 12,
          "title": "Dexter",
          "Ratings": 8.7,
          "Duration (in Min)": 53,
          "thumbnail":"https://i.pinimg.com/736x/2d/eb/f3/2debf3d2572a02ab2a9bfe2d9c48fae6.jpg",
          "Votes": 719802,
          "year": 2006,
          "genres": "Crime",
          "Summary": "He's smart. He's lovable. He's Dexter Morgan, America's favorite serial killer, who spends his days solving crimes and nights committing them. Golden Globe winner Michael C. Hall stars in the hit SHOWTIME Original Series."
        },
        {
          "Sr.No": 13,
          "title": "Bates Motel",
          "Ratings": 8.1,
          "Duration (in Min)": 45,
          "thumbnail":"https://i.pinimg.com/736x/0a/e0/4c/0ae04ccf149e19346c8b31da55ef56fb.jpg",
          "Votes": 107076,
          "year": 2013,
          "genres": "Drama",
          "Summary": "A contemporary prequel to Psycho, giving a portrayal of how Norman Bates' psyche unravels through his teenage years, and how deeply intricate his relationship with his mother, Norma, truly is."
        },
        {
          "Sr.No": 14,
          "title": "Asur: Welcome to Your Dark Side",
          "Ratings": 8.4,
          "Duration (in Min)": 43,
          "thumbnail":"https://i.pinimg.com/736x/03/30/46/033046383e222de0b77916f31cf2528d.jpg",
          "Votes": 41093,
          "year": 2020,
          "genres": "Crime",
          "Summary": "A unique crime thriller that pits two opposing worlds against each other. The less explored, intricate world of forensic science and the deep mysticism of ancient Indian Mythology."
        },
        {
          "Sr.No": 15,
          "title": "Fosse/Verdon",
          "Ratings": 7.9,
          "Duration (in Min)": 402,
          "thumbnail":"https://i.pinimg.com/564x/11/12/62/111262da3234be9f0ad77699eafdbfdd.jpg",
          "Votes": 6398,
          "year": 2019,
          "genres": "Biography",
          "Summary": "An inside look at the romantic and creative partnership between influential choreographer/director, Bob Fosse, and Gwen Verdon, one of the greatest Broadway dancers of all time."
        },
        {
          "Sr.No": 16,
          "title": "Euphoria",
          "Ratings": 8.4,
          "Duration (in Min)": 55,
          "thumbnail":"https://i.pinimg.com/736x/f1/70/d9/f170d92de1d20e60b928ce5a4b582970.jpg",
          "Votes": 174642,
          "year": 2019,
          "genres": "Drama",
          "Summary": "A look at life for a group of high school students as they grapple with issues of drugs, sex, and violence."
        },
        {
          "Sr.No": 17,
          "title": "Killing Eve",
          "Ratings": 8.1,
          "Duration (in Min)": 42,
          "thumbnail":"https://i.pinimg.com/564x/8f/34/35/8f3435cfd9500f8ff856959c0ec9f0c2.jpg",
          "Votes": 117091,
          "year": 2018,
          "genres": "Action",
          "Summary": "After a series of events, the lives of a security operative and an assassin become inextricably linked."
        },
        {
          "Sr.No": 18,
          "title": "Succession",
          "Ratings": 8.8,
          "Duration (in Min)": 60,
          "thumbnail":"https://i.pinimg.com/736x/41/f5/11/41f511616c0390609e0ebcf667e62028.jpg",
          "Votes": 137934,
          "year": 2018,
          "genres": "Drama",
          "Summary": "The Roy family is known for controlling the biggest media and entertainment company in the world. However, their world changes when their father steps down from the company."
        },
        {
          "Sr.No": 19,
          "title": "Kota Factory",
          "Ratings": 8.3,
          "Duration (in Min)": 30,
          "thumbnail":"https://i.pinimg.com/564x/89/15/60/8915603a84b1f714540390dc1938be2b.jpg",
          "Votes": 45633,
          "year": 2018,
          "genres": "Drama",
          "Summary": "While strange rumors about their ill King grip a kingdom, the crown prince becomes their only hope against a mysterious plague overtaking the land."
        },
        {
          "Sr.No": 20,
          "title": "Six Feet Under",
          "Ratings": 8.7,
          "Duration (in Min)": 60,
          "thumbnail":"https://i.pinimg.com/564x/99/ac/e1/99ace106a54db406636fce845ed914af.jpg",
          "Votes": 134203,
          "year": 2001,
          "genres": "Comedy",
          "Summary": "A chronicle of the lives of a dysfunctional family who run an independent funeral home in Los Angeles."
        },
        {
          "Sr.No": 21,
          "title": "Paatalok",
          "Ratings": 8.3,
          "Duration (in Min)": 60,
          "thumbnail":"https://i.pinimg.com/564x/93/90/1e/93901e8a64d900f2ad04485028111e58.jpg",
          "Votes": 32858,
          "year": 2019,
          "genres": "Crime",
          "Summary": "A group of genetically-enhanced children escape from a lab project. Years later we meet Max, one of the escapees who now works for a messenger service in the post-apocalyptic Pacific Northwest."
        },
        {
          "Sr.No": 22,
          "title": "Doom Patrol",
          "Ratings": 7.8,
          "Duration (in Min)": 60,
          "thumbnail":"https://i.pinimg.com/736x/0e/60/7d/0e607d088b9d99c1a4a56259697edf65.jpg",
          "Votes": 51190,
          "year": 2019,
          "genres": "Action",
          "Summary": "The adventures of an idealistic mad scientist and his field team of superpowered outcasts."
        },
        {
          "Sr.No": 23,
          "title": "Class",
          "Ratings": 7.4,
          "Duration (in Min)": 60,
          "thumbnail":"https://i.pinimg.com/564x/06/44/85/064485f636bb70826554ab6cf46b002d.jpg",
          "Votes": 25062,
          "year": 2023,
          "genres": "Drama",
          "Summary": "Abby Arcane returns home to Marais, Louisiana to investigate a deadly swamp-borne virus, only to discover the dark, terrifying mysteries of the swamp."
        },
        {
          "Sr.No": 24,
          "title": "Chilling Adventures of Sabrina",
          "Ratings": 7.4,
          "Duration (in Min)": 60,
          "thumbnail":"https://i.pinimg.com/564x/26/18/48/261848b4953541b131abf38bd06ca927.jpg",
          "Votes": 93289,
          "year": 2018,
          "genres": "Drama",
          "Summary": "As her 16th birthday nears, Sabrina must choose between the witch world of her family and the human world of her friends. Based on the Archie comic."
        },
        {
          "Sr.No": 25,
          "title": "Scam 1992",
          "Ratings": 8.9,
          "Duration (in Min)": 60,
          "thumbnail":"https://i.pinimg.com/564x/e0/1e/7f/e01e7f90fd11b83c196f063cedb9ebf4.jpg",
          "Votes": 44612,
          "year": 2021,
          "genres": "Biography",
          "Summary": "Supernatural, semihistorical, horror anthology series, where each season is inspired by a different infamous or mysterious real life historical tragedy."
        },
        {
          "Sr.No": 26,
          "title": "Channel Zero",
          "Ratings": 7.1,
          "Duration (in Min)": 44,
          "thumbnail":"https://i.pinimg.com/736x/57/3f/f3/573ff3c871c1ca23e576e921075bf78b.jpg",
          "Votes": 10750,
          "year": 2016,
          "genres": "Crime",
          "Summary": "An anthology series based on popular Internet Creepypastas Candle Cove, The No-End House, Butcher's Block, and The Dream Door."
        },
        {
          "Sr.No": 27,
          "title": "Hannibal",
          "Ratings": 8.5,
          "Duration (in Min)": 44,
          "thumbnail":"https://i.pinimg.com/564x/9f/f6/ee/9ff6eeddd98f30fc36d5858c3e61fea3.jpg",
          "Votes": 252742,
          "year": 2013,
          "genres": "Crime",
          "Summary": "Explores the early relationship between renowned psychiatrist Hannibal Lecter and a young FBI criminal profiler who is haunted by his ability to empathize with serial killers."
        },
        {
          "Sr.No": 28,
          "title": "Dark",
          "Ratings": 8.7,
          "Duration (in Min)": 60,
          "thumbnail":"https://i.pinimg.com/564x/94/00/10/940010831c9010d9bea0f40aff4c5fdb.jpg",
          "Votes": 369700,
          "year": 2017,
          "genres": "Crime",
          "Summary": "A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the relationships among four families."
        },
        {
          "Sr.No": 29,
          "title": "The Haunting of Hill House",
          "Ratings": 8.6,
          "Duration (in Min)": 572,
          "thumbnail":"https://i.pinimg.com/564x/82/bd/0b/82bd0b3008e779f0d92088fbac8dd5c2.jpg",
          "Votes": 235900,
          "year": 2018,
          "genres": "Drama",
          "Summary": "Flashing between past and present, a fractured family confronts haunting memories of their old home and the terrifying events that drove them from it."
        },
        {
          "Sr.No": 30,
          "title": "The Originals",
          "Ratings": 8.3,
          "Duration (in Min)": 45,
          "thumbnail":"https://i.pinimg.com/564x/2b/f9/10/2bf910eba6f3c296bf1fe2c16d83614a.jpg",
          "Votes": 134562,
          "year": 2013,
          "genres": "Drama",
          "Summary": "A family of power-hungry thousand-year-old vampires look to take back the city that they built and dominate all those who have done them wrong."
        },
        {
            "Sr.No": 31,
            "title": "Panchayat",
            "Ratings": 8.4,
            "Duration (in Min)": 45,
            "thumbnail":"https://i.pinimg.com/236x/6c/7b/e5/6c7be5669234cbfca89794f6d17943b1.jpg",
            "Votes": 51190,
            "year": 2019,
            "genres": "Action",
            "Summary": "The adventures of an idealistic mad scientist and his field team of superpowered outcasts."
        }
]
export default tvdata;