[
    {
      "show_id": "s2",
      "type": "TV Show",
      "title": "Blood & Water",
      "director": "",
      "cast": "Ama Qamata, Khosi Ngema, Gail Mabalane, Thabang Molaba, Dillon Windvogel, Natasha Thahane, Arno Greeff, Xolile Tshabalala, Getmore Sithole, Cindy Mahlangu, Ryle De Morny, Greteli Fincham, Sello Maake Ka-Ncube, Odwa Gwanya, Mekaila Mathys, Sandi Schultz, Duane Williams, Shamilla Miller, Patrick Mofokeng",
      "country": "South Africa",
      "date_added": "September 24, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "2 Seasons",
      "listed_in": "Mystery",
      "description": "After crossing paths at a party, a Cape Town teen sets out to prove whether a private-school swimming star is her sister who was abducted at birth."
    },
    {
      "show_id": "s3",
      "type": "TV Show",
      "title": "Ganglands",
      "director": "Julien Leclercq",
      "cast": "Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabiha Akkari, Sofia Lesaffre, Salim Kechiouche, Noureddine Farihi, Geert Van Rampelberg, Bakary Diombera",
      "country": "",
      "date_added": "September 24, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "Action & Adventure",
      "description": "To protect his family from a powerful drug lord, skilled thief Mehdi and his expert team of robbers are pulled into a violent and deadly turf war."
    },
    {
      "show_id": "s4",
      "type": "TV Show",
      "title": "Jailbirds New Orleans",
      "director": "",
      "cast": "",
      "country": "",
      "date_added": "September 24, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "Docuseries",
      "description": "Feuds, flirtations and toilet talk go down among the incarcerated women at the Orleans Justice Center in New Orleans on this gritty reality series."
    },
    {
      "show_id": "s5",
      "type": "TV Show",
      "title": "Kota Factory",
      "director": "",
      "cast": "Mayur More, Jitendra Kumar, Ranjan Raj, Alam Khan, Ahsaas Channa, Revathi Pillai, Urvi Singh, Arun Kumar",
      "country": "India",
      "date_added": "September 24, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "2 Seasons",
      "listed_in": "Drama",
      "description": "In a city of coaching centers known to train India’s finest collegiate minds, an earnest but unexceptional student and his friends navigate campus life."
    },
    {
      "show_id": "s6",
      "type": "TV Show",
      "title": "Midnight Mass",
      "director": "Mike Flanagan",
      "cast": "Kate Siegel, Zach Gilford, Hamish Linklater, Henry Thomas, Kristin Lehman, Samantha Sloyan, Igby Rigney, Rahul Kohli, Annarah Cymone, Annabeth Gish, Alex Essoe, Rahul Abburi, Matt Biedel, Michael Trucco, Crystal Balint, Louis Oliver",
      "country": "",
      "date_added": "September 24, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "Horror",
      "description": "The arrival of a charismatic young priest brings glorious miracles, ominous mysteries and renewed religious fervor to a dying town desperate to believe."
    },
    {
      "show_id": "s9",
      "type": "TV Show",
      "title": "The Great British Baking Show",
      "director": "Andy Devonshire",
      "cast": "Mel Giedroyc, Sue Perkins, Mary Berry, Paul Hollywood",
      "country": "United Kingdom",
      "date_added": "September 24, 2021",
      "release_year": 2021,
      "rating": "TV-14",
      "duration": "9 Seasons",
      "listed_in": "British",
      "description": "A talented batch of amateur bakers face off in a 10-week competition, whipping up their best dishes in the hopes of being named the U.K.'s best."
    },
    {
      "show_id": "s11",
      "type": "TV Show",
      "title": "Vendetta: Truth, Lies and The Mafia",
      "director": "",
      "cast": "",
      "country": "",
      "date_added": "September 24, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "Crime",
      "description": "Sicily boasts a bold \"Anti-Mafia\" coalition. But what happens when those trying to bring down organized crime are accused of being criminals themselves?"
    },
    {
      "show_id": "s12",
      "type": "TV Show",
      "title": "Bangkok Breaking",
      "director": "Kongkiat Komesiri",
      "cast": "Sukollawat Kanarot, Sushar Manaying, Pavarit Mongkolpisit, Sahajak Boonthanakit, Suthipongse Thatphithakkul, Bhasaworn Bawronkirati, Daweerit Chullasapya, Waratthaya Wongchayaporn, Kittiphoom Wongpentak, Abhicha Thanachanun, Nophand Boonyai, Kittipong Khamsat, Arisara Wongchalee, Jaytiya Naiwattanakul, Pantipa Arunwattanachai, Panupan Jantanawong, Kungtap Saelim, Phumphat Chartsuriyakiat, Issara Veranitinunt, Keerati Sivakuae, Panjai Sirisuwan, Supranee Charoenpol, Suda Chuenban, Visaka Banhansupavat, Pitchatorn Santinatornkul",
      "country": "",
      "date_added": "September 23, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "Crime",
      "description": "Struggling to earn a living in Bangkok, a man joins an emergency rescue service and realizes he must unravel a citywide conspiracy."
    },
    {
      "show_id": "s15",
      "type": "TV Show",
      "title": "Crime Stories: India Detectives",
      "director": "",
      "cast": "",
      "country": "",
      "date_added": "September 22, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "British",
      "description": "Cameras following Bengaluru police on the job offer a rare glimpse into the complex and challenging inner workings of four major crime investigations."
    },
    {
      "show_id": "s16",
      "type": "TV Show",
      "title": "Dear White People",
      "director": "",
      "cast": "Logan Browning, Brandon P. Bell, DeRon Horton, Antoinette Robertson, John Patrick Amedori, Ashley Blaine Featherson, Marque Richardson, Giancarlo Esposito",
      "country": "United States",
      "date_added": "September 22, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "4 Seasons",
      "listed_in": "Dramas",
      "description": "Students of color navigate the daily slights and slippery politics of life at an Ivy League college that's not nearly as \"post-racial\" as it thinks."
    },
    {
      "show_id": "s18",
      "type": "TV Show",
      "title": "Falsa identidad",
      "director": "",
      "cast": "Luis Ernesto Franco, Camila Sodi, Sergio Goyri, Samadhi Zendejas, Eduardo Yáñez, Sonya Smith, Alejandro Camacho, Azela Robinson, Uriel del Toro, Géraldine Bazán, Gabriela Roel, Marcus Ornellas",
      "country": "Mexico",
      "date_added": "September 22, 2021",
      "release_year": 2020,
      "rating": "TV-MA",
      "duration": "2 Seasons",
      "listed_in": "Crime",
      "description": "Strangers Diego and Isabel flee their home in Mexico and pretend to be a married couple to escape his drug-dealing enemies and her abusive husband."
    },
    {
      "show_id": "s20",
      "type": "TV Show",
      "title": "Jaguar",
      "director": "",
      "cast": "Blanca Suárez, Iván Marcos, Óscar Casas, Adrián Lastra, Francesc Garrido, Stefan Weinert, Julia Möller, Alicia Chojnowski",
      "country": "",
      "date_added": "September 22, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "Action & Adventure",
      "description": "In the 1960s, a Holocaust survivor joins a group of self-trained spies who seek justice against Nazis fleeing to Spain to hide after WWII."
    },
    {
      "show_id": "s21",
      "type": "TV Show",
      "title": "Monsters Inside: The 24 Faces of Billy Milligan",
      "director": "Olivier Megaton",
      "cast": "",
      "country": "",
      "date_added": "September 22, 2021",
      "release_year": 2021,
      "rating": "TV-14",
      "duration": "1 Season",
      "listed_in": "Crime",
      "description": "In the late 1970s, an accused serial rapist claims multiple personalities control his behavior, setting off a legal odyssey that captivates America."
    },
    {
      "show_id": "s26",
      "type": "TV Show",
      "title": "Love on the Spectrum",
      "director": "",
      "cast": "Brooke Satchwell",
      "country": "Australia",
      "date_added": "September 21, 2021",
      "release_year": 2021,
      "rating": "TV-14",
      "duration": "2 Seasons",
      "listed_in": "Docuseries, International TV Shows, Reality TV",
      "description": "Finding love can be hard for anyone. For young adults on the autism spectrum, exploring the unpredictable world of dating is even more complicated."
    },
    {
      "show_id": "s32",
      "type": "TV Show",
      "title": "Chicago Party Aunt",
      "director": "",
      "cast": "Lauren Ash, Rory O'Malley, RuPaul Charles, Jill Talley, Ike Barinholtz, Jon Barinholtz, Matthew Craig, Bob Odenkirk, Mike Hagerty, Katie Rich, Chris Witaske",
      "country": "",
      "date_added": "September 17, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "Comedy",
      "description": "Chicago Party Aunt Diane is an idolized troublemaker with a talent for avoiding adulthood — and a soft spot for her soul-searching nephew."
    },
    {
      "show_id": "s33",
      "type": "TV Show",
      "title": "Sex Education",
      "director": "",
      "cast": "Asa Butterfield, Gillian Anderson, Ncuti Gatwa, Emma Mackey, Connor Swindells, Kedar Williams-Stirling, Alistair Petrie",
      "country": "United Kingdom",
      "date_added": "September 17, 2021",
      "release_year": 2020,
      "rating": "TV-MA",
      "duration": "3 Seasons",
      "listed_in": "Comedy",
      "description": "Insecure Otis has all the answers when it comes to sex advice, thanks to his therapist mom. So rebel Maeve proposes a school sex-therapy clinic."
    },
    {
      "show_id": "s34",
      "type": "TV Show",
      "title": "Squid Game",
      "director": "",
      "cast": "Lee Jung-jae, Park Hae-soo, Wi Ha-jun, Oh Young-soo, Jung Ho-yeon, Heo Sung-tae, Kim Joo-ryoung, Tripathi Anupam, You Seong-joo, Lee You-mi",
      "country": "",
      "date_added": "September 17, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "Drama",
      "description": "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits — with deadly high stakes."
    },
    {
      "show_id": "s36",
      "type": "Movie",
      "title": "The Father Who Moves Mountains",
      "director": "Daniel Sandu",
      "cast": "Adrian Titieni, Elena Purea, Judith State, Valeriu Andriuță, Tudor Smoleanu, Virgil Aioanei, Radu Botar, Petronela Grigorescu, Bogdan Nechifor, Cristian Bota",
      "country": "",
      "date_added": "September 17, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "110 min",
      "listed_in": "Thrillers",
      "description": "When his son goes missing during a snowy hike in the mountains, a retired intelligence officer will stop at nothing — and risk everything — to find him."
    },
    {
      "show_id": "s38",
      "type": "TV Show",
      "title": "Angry Birds",
      "director": "",
      "cast": "Antti Pääkkönen, Heljä Heikkinen, Lynne Guaglione, Pasi Ruohonen, Rauno Ahonen",
      "country": "Finland",
      "date_added": "September 16, 2021",
      "release_year": 2018,
      "rating": "TV-Y7",
      "duration": "1 Season",
      "listed_in": "Kids",
      "description": "Birds Red, Chuck and their feathered friends have lots of adventures while guarding eggs in their nest that pesky pigs keep trying to steal."
    },
    {
      "show_id": "s40",
      "type": "TV Show",
      "title": "Chhota Bheem",
      "director": "",
      "cast": "Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jigna Bhardwaj, Rajesh Kava, Mousam, Swapnil",
      "country": "India",
      "date_added": "September 16, 2021",
      "release_year": 2021,
      "rating": "TV-Y7",
      "duration": "3 Seasons",
      "listed_in": "Kids",
      "description": "A brave, energetic little boy with superhuman powers leads his friends on exciting adventures to guard their fellow Dholakpur villagers from evil."
    },
    {
      "show_id": "s41",
      "type": "TV Show",
      "title": "He-Man and the Masters of the Universe",
      "director": "",
      "cast": "Yuri Lowenthal, Kimberly Brooks, Antony Del Rio, Trevor Devall, Ben Diskin, Grey Griffin, David Kaye, Tom Kenny, Judy Alice Lee, Roger Craig Smith, Fred Tatasciore",
      "country": "United States",
      "date_added": "September 16, 2021",
      "release_year": 2021,
      "rating": "TV-Y7",
      "duration": "1 Season",
      "listed_in": "Kids",
      "description": "Mighty teen Adam and his heroic squad of misfits discover the legendary power of Grayskull — and their destiny to defend Eternia from sinister Skeletor."
    },
    {
      "show_id": "s48",
      "type": "TV Show",
      "title": "The Smart Money Woman",
      "director": "Bunmi Ajakaiye",
      "cast": "Osas Ighodaro, Ini Dima-Okojie, Kemi Lala Akindoju, Toni Tones, Ebenezer Eno, Eso Okolocha DIke, Patrick Diabuah, Karibi Fubara, Temisan Emmanuel, Timini Egbuson",
      "country": "",
      "date_added": "September 16, 2021",
      "release_year": 2020,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "Comedy",
      "description": "Five glamorous millennials strive for success as they juggle careers, finances, love and friendships. Based on Arese Ugwu's 2016 best-selling novel."
    },
    {
      "show_id": "s50",
      "type": "TV Show",
      "title": "Castle and Castle",
      "director": "",
      "cast": "Richard Mofe-Damijo, Dakore Akande, Bimbo Manuel, Blossom Chukwujekwu, Deyemi Okanlawon, Etim Effiong, Denola Grey, Duke Akintola, Eku Edewor, Ade Laoye, Anee Icha, Kevin Ushi, Jude Chukwuka, Amanda Afolabi",
      "country": "Nigeria",
      "date_added": "September 15, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "2 Seasons",
      "listed_in": "Drama",
      "description": "A pair of high-powered, successful lawyers find themselves defending opposite interests of the justice system, causing a strain on their happy marriage."
    },
    {
      "show_id": "s51",
      "type": "TV Show",
      "title": "Dharmakshetra",
      "director": "",
      "cast": "Kashmira Irani, Chandan Anand, Dinesh Mehta, Ankit Arora, Pushkar Goggiaa, Anjali Rana, Aarya DharmChand Kumar, Amit Behl, Maleeka Ghai",
      "country": "India",
      "date_added": "September 15, 2021",
      "release_year": 2014,
      "rating": "TV-PG",
      "duration": "1 Season",
      "listed_in": "Sci-Fi & Fantasy",
      "description": "After the ancient Great War, the god Chitragupta oversees a trial to determine who were the battle's true heroes and villains."
    },
    {
      "show_id": "s66",
      "type": "TV Show",
      "title": "Numberblocks",
      "director": "",
      "cast": "Beth Chalmers, David Holt, Marcel McCalla, Teresa Gallagher",
      "country": "United Kingdom",
      "date_added": "September 15, 2021",
      "release_year": 2021,
      "rating": "TV-Y",
      "duration": "6 Seasons",
      "listed_in": "Kids",
      "description": "In a place called Numberland, math adds up to tons of fun when a group of cheerful blocks work, play and sing together."
    },
    {
      "show_id": "s67",
      "type": "TV Show",
      "title": "Raja Rasoi Aur Anya Kahaniyan",
      "director": "",
      "cast": "",
      "country": "India",
      "date_added": "September 15, 2021",
      "release_year": 2014,
      "rating": "TV-G",
      "duration": "1 Season",
      "listed_in": "Docuseries",
      "description": "Explore the history and flavors of regional Indian cuisine, from traditional Kashmiri feasts to the vegetarian dishes of Gujarat."
    },
    {
      "show_id": "s68",
      "type": "TV Show",
      "title": "Saved by the Bell",
      "director": "",
      "cast": "Mark-Paul Gosselaar, Tiffani Thiessen, Mario Lopez, Lark Voorhies, Elizabeth Berkley, Dustin Diamond, Dennis Haskins",
      "country": "United States",
      "date_added": "September 15, 2021",
      "release_year": 1994,
      "rating": "TV-PG",
      "duration": "9 Seasons",
      "listed_in": "Kids",
      "description": "From middle school to college, best friends Zack, Kelly, Slater, Jessie, Screech and Lisa take on the highs and lows of life together in this hit series."
    },
    {
      "show_id": "s70",
      "type": "TV Show",
      "title": "Stories by Rabindranath Tagore",
      "director": "",
      "cast": "",
      "country": "India",
      "date_added": "September 15, 2021",
      "release_year": 2015,
      "rating": "TV-PG",
      "duration": "1 Season",
      "listed_in": "Drama",
      "description": "The writings of Nobel Prize winner Rabindranath Tagore come to life in this collection of tales set in early-20th-century Bengal."
    },
    {
      "show_id": "s73",
      "type": "TV Show",
      "title": "Jack Whitehall: Travels with My Father",
      "director": "",
      "cast": "Jack Whitehall, Michael Whitehall",
      "country": "United Kingdom",
      "date_added": "September 14, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "5 Seasons",
      "listed_in": "British",
      "description": "Jovial comic Jack Whitehall invites his stuffy father, Michael, to travel with him through Southeast Asia in an attempt to strengthen their bond."
    },
    {
      "show_id": "s75",
      "type": "TV Show",
      "title": "The World's Most Amazing Vacation Rentals",
      "director": "",
      "cast": "",
      "country": "",
      "date_added": "September 14, 2021",
      "release_year": 2021,
      "rating": "TV-PG",
      "duration": "2 Seasons",
      "listed_in": "Reality TV",
      "description": "With an eye for every budget, three travelers visit vacation rentals around the globe and share their expert tips and tricks in this reality series."
    },
    {
      "show_id": "s77",
      "type": "TV Show",
      "title": "Yowamushi Pedal",
      "director": "",
      "cast": "Daiki Yamashita, Kohsuke Toriumi, Jun Fukushima, Hiroki Yasumoto, Showtaro Morikubo, Kentaro Ito, Daisuke Kishio, Yoshitsugu Matsuoka, Junichi Suwabe, Ayaka Suwa, Megumi Han, Tomoaki Maeno, Tsubasa Yonaga, Tetsuya Kakihara, Satoshi Hino, Hiroyuki Yoshino, Atsushi Abe, Koji Yusa, Kouki Miyata, Hiro Shimono, Wataru Hatano, Yuichi Nakamura, Kenji Nojima, Mamoru Miyano, Daisuke Ono, Yuma Uchida, Jun Fukuyama",
      "country": "Japan",
      "date_added": "September 14, 2021",
      "release_year": 2013,
      "rating": "TV-14",
      "duration": "1 Season",
      "listed_in": "Anime",
      "description": "A timid, anime-loving teen gets drawn into a school cycling club, where his new friends help him face tough challenges to develop his racing talent."
    },
    {
      "show_id": "s83",
      "type": "TV Show",
      "title": "Lucifer",
      "director": "",
      "cast": "Tom Ellis, Lauren German, Kevin Alejandro, D.B. Woodside, Lesley-Ann Brandt, Scarlett Estevez, Rachael Harris, Aimee Garcia, Tricia Helfer, Tom Welling, Jeremiah W. Birkett, Pej Vahdat, Michael Gladis",
      "country": "United States",
      "date_added": "September 10, 2021",
      "release_year": 2021,
      "rating": "TV-14",
      "duration": "6 Seasons",
      "listed_in": "Crime",
      "description": "Bored with being the Lord of Hell, the devil relocates to Los Angeles, where he opens a nightclub and forms a connection with a homicide detective."
    },
    {
      "show_id": "s84",
      "type": "TV Show",
      "title": "Metal Shop Masters",
      "director": "",
      "cast": "Jo Koy",
      "country": "",
      "date_added": "September 10, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "Reality TV",
      "description": "On this competition show, a group of metal artists torch, cut and weld epic, badass creations from hardened steel. Only one will win a $50,000 prize."
    },
    {
      "show_id": "s86",
      "type": "TV Show",
      "title": "Pokémon Master Journeys: The Series",
      "director": "",
      "cast": "Ikue Otani, Sarah Natochenny, Zeno Robinson, Cherami Leigh, James Carter Cathcart, Michele Knotz, Rodger Parsons, Ray Chase, Casey Mongillo, Tara Sands",
      "country": "",
      "date_added": "September 10, 2021",
      "release_year": 2021,
      "rating": "TV-Y7",
      "duration": "1 Season",
      "listed_in": "Anime",
      "description": "As Ash battles his way through the World Coronation Series, Goh continues his quest to catch every Pokémon. Together, they're on a journey to adventure!"
    },
    {
      "show_id": "s88",
      "type": "TV Show",
      "title": "Titipo Titipo",
      "director": "",
      "cast": "Jeon Hae-ri, Kim Eun-ah, Hong Bum-ki, Nam Do-hyeong, Um Sang-hyun",
      "country": "",
      "date_added": "September 10, 2021",
      "release_year": 2019,
      "rating": "TV-Y",
      "duration": "2 Seasons",
      "listed_in": "Kids",
      "description": "Titipo the train is out to prove that he's got what it takes to help the folks of Train Village ride the rails safely and reliably."
    },
    {
      "show_id": "s89",
      "type": "Movie",
      "title": "Blood Brothers: Malcolm X & Muhammad Ali",
      "director": "Marcus Clarke",
      "cast": "Malcolm X, Muhammad Ali",
      "country": "",
      "date_added": "September 9, 2021",
      "release_year": 2021,
      "rating": "PG-13",
      "duration": "96 min",
      "listed_in": "Documentaries",
      "description": "From a chance meeting to a tragic fallout, Malcolm X and Muhammad Ali's extraordinary bond cracks under the weight of distrust and shifting ideals."
    },
    {
      "show_id": "s90",
      "type": "TV Show",
      "title": "Mighty Raju",
      "director": "",
      "cast": "Julie Tejwani, Sabina Malik, Jigna Bhardwaj, Rupa Bhimani, Lalit Agarwal, Rajesh Shukla, Rajesh Kava",
      "country": "",
      "date_added": "September 9, 2021",
      "release_year": 2017,
      "rating": "TV-Y7",
      "duration": "4 Seasons",
      "listed_in": "Kids",
      "description": "Born with superhuman abilities, young Raju wants to use his powers to make the world a better place — but that will mean facing plenty of challenges!"
    },
    {
      "show_id": "s91",
      "type": "Movie",
      "title": "Paradise Hills",
      "director": "Alice Waddington",
      "cast": "Emma Roberts, Danielle Macdonald, Awkwafina, Eiza González, Milla Jovovich, Jeremy Irvine, Arnaud Valois, Daniel Horvath",
      "country": "Spain, United States",
      "date_added": "September 9, 2021",
      "release_year": 2019,
      "rating": "TV-MA",
      "duration": "95 min",
      "listed_in": "Sci-Fi & Fantasy",
      "description": "Uma wakes up in a lush tropical facility designed to turn willful girls into perfect ladies. That’s bad enough, but its real purpose is even worse."
    },
    {
      "show_id": "s92",
      "type": "Movie",
      "title": "The Women and the Murderer",
      "director": "Mona Achache, Patricia Tourancheau",
      "cast": "",
      "country": "France",
      "date_added": "September 9, 2021",
      "release_year": 2021,
      "rating": "TV-14",
      "duration": "92 min",
      "listed_in": "Documentaries, International Movies",
      "description": "This documentary traces the capture of serial killer Guy Georges through the tireless work of two women: a police chief and a victim's mother."
    },
    {
      "show_id": "s93",
      "type": "TV Show",
      "title": "Into the Night",
      "director": "",
      "cast": "Pauline Etienne, Laurent Capelluto, Stefano Cassetti, Mehmet Kurtuluş, Babetida Sadjo, Jan Bijvoet, Ksawery Szlenkier, Vincent Londez, Regina Bikkinina, Alba Gaïa Kraghede Bellugi, Nabil Mallat",
      "country": "Belgium",
      "date_added": "September 8, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "2 Seasons",
      "listed_in": "International TV Shows, TV Dramas, TV Mysteries",
      "description": "Passengers and crew aboard a hijacked overnight flight scramble to outrace the sun as a mysterious cosmic event wreaks havoc on the world below."
    },
    {
      "show_id": "s94",
      "type": "Movie",
      "title": "JJ+E",
      "director": "Alexis Almström",
      "cast": "Elsa Öhrn, Mustapha Aarab, Jonay Pineda Skallak, Magnus Krepper, Loreen, Albin Grenholm, Simon Mezher, Elsa Bergström Terent, Josef Kadim, Yohannes Frezgi",
      "country": "",
      "date_added": "September 8, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "91 min",
      "listed_in": "Dramas, International Movies, Romantic Movies",
      "description": "Elisabeth and John-John live in the same city, but they inhabit different worlds. Can a passionate first love break through class and cultural barriers?"
    },
    {
      "show_id": "s95",
      "type": "Movie",
      "title": "Show Dogs",
      "director": "Raja Gosnell",
      "cast": "Will Arnett, Ludacris, Natasha Lyonne, Stanley Tucci, Jordin Sparks, Gabriel Iglesias, Shaquille O'Neal, Omar Chaparro, Alan Cumming, Andy Beckwith, Delia Sheppard, Kerry Shale",
      "country": "United Kingdom, United States",
      "date_added": "September 8, 2021",
      "release_year": 2018,
      "rating": "PG",
      "duration": "90 min",
      "listed_in": "Children & Family Movies, Comedies",
      "description": "A rough and tough police dog must go undercover with an FBI agent as a prim and proper pet at a dog show to save a baby panda from an illegal sale."
    },
    {
      "show_id": "s96",
      "type": "TV Show",
      "title": "The Circle",
      "director": "",
      "cast": "Michelle Buteau",
      "country": "United States, United Kingdom",
      "date_added": "September 8, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "3 Seasons",
      "listed_in": "Reality TV",
      "description": "Status and strategy collide in this social experiment and competition show where online players flirt, befriend and catfish their way toward $100,000."
    },
    {
      "show_id": "s97",
      "type": "Movie",
      "title": "If I Leave Here Tomorrow: A Film About Lynyrd Skynyrd",
      "director": "Stephen Kijak",
      "cast": "Ronnie Van Zandt, Gary Rossington, Allen Collins, Leon Wilkeson, Bob Burns, Billy Powell, Ed King, Artimus Pyle, Steve Gaines, Johnny Van Zant",
      "country": "United States",
      "date_added": "September 7, 2021",
      "release_year": 2018,
      "rating": "TV-MA",
      "duration": "97 min",
      "listed_in": "Documentaries, Music & Musicals",
      "description": "Using interviews and archival footage, this documentary charts the story of the legendary Southern rockers with a focus on front man Ronnie Van Zant."
    },
    {
      "show_id": "s98",
      "type": "TV Show",
      "title": "Kid Cosmic",
      "director": "",
      "cast": "Jack Fisher, Tom Kenny, Amanda C. Miller, Kim Yarbrough, Keith Ferguson, Grey Griffin, Lily Rose Silver",
      "country": "United States",
      "date_added": "September 7, 2021",
      "release_year": 2021,
      "rating": "TV-Y7",
      "duration": "2 Seasons",
      "listed_in": "Kids' TV, TV Comedies, TV Sci-Fi & Fantasy",
      "description": "A boy's superhero dreams come true when he finds five powerful cosmic stones. But saving the day is harder than he imagined — and he can't do it alone."
    },
    {
      "show_id": "s99",
      "type": "TV Show",
      "title": "Octonauts: Above & Beyond",
      "director": "",
      "cast": "Antonio Aakeel, Chipo Chung, Simon Foster, Teresa Gallagher, Simon Greenall, Kate Harbour, Paul Panting, Rob Rackstraw, William Vanderpuye, Helen Walsh, Keith Wickham, Andres Williams, Jo Wyatt",
      "country": "United Kingdom",
      "date_added": "September 7, 2021",
      "release_year": 2021,
      "rating": "TV-Y",
      "duration": "1 Season",
      "listed_in": "British TV Shows, Kids' TV",
      "description": "The Octonauts expand their exploration beyond the sea — and onto land! With new rides and new friends, they'll protect any habitats and animals at risk."
    },
    {
      "show_id": "s100",
      "type": "TV Show",
      "title": "On the Verge",
      "director": "",
      "cast": "Julie Delpy, Elisabeth Shue, Sarah Jones, Alexia Landeau, Mathieu Demy, Troy Garity, Timm Sharp, Giovanni Ribisi",
      "country": "France, United States",
      "date_added": "September 7, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "TV Comedies, TV Dramas",
      "description": "Four women — a chef, a single mom, an heiress and a job seeker — dig into love and work, with a generous side of midlife crises, in pre-pandemic LA."
    },
    {
      "show_id": "s101",
      "type": "TV Show",
      "title": "Tobot Galaxy Detectives",
      "director": "",
      "cast": "Austin Abell, Travis Turner, Cole Howard, Anna Cummer, Jesse Inocalla, Brian Dobson, Michael Adamthwaite, Joseph Girgis, Caitlyn Bairstow",
      "country": "",
      "date_added": "September 7, 2021",
      "release_year": 2019,
      "rating": "TV-Y7",
      "duration": "2 Seasons",
      "listed_in": "Kids' TV",
      "description": "An intergalactic device transforms toy cars into robots: the Tobots! Working with friends to solve mysteries, they protect the world from evil."
    },
    {
      "show_id": "s102",
      "type": "Movie",
      "title": "Untold: Breaking Point",
      "director": "Chapman Way, Maclain Way",
      "cast": "",
      "country": "United States",
      "date_added": "September 7, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "80 min",
      "listed_in": "Documentaries, Sports Movies",
      "description": "Under pressure to continue a winning tradition in American tennis, Mardy Fish faced mental health challenges that changed his life on and off the court."
    },
    {
      "show_id": "s103",
      "type": "TV Show",
      "title": "Countdown: Inspiration4 Mission to Space",
      "director": "Jason Hehir",
      "cast": "",
      "country": "",
      "date_added": "September 6, 2021",
      "release_year": 2021,
      "rating": "TV-14",
      "duration": "1 Season",
      "listed_in": "Docuseries, Science & Nature TV",
      "description": "From training to launch to landing, this all-access docuseries rides along with the Inspiration4 crew on the first all-civilian orbital space mission."
    },
    {
      "show_id": "s104",
      "type": "Movie",
      "title": "Shadow Parties",
      "director": "Yemi Amodu",
      "cast": "Jide Kosoko, Omotola Jalade-Ekeinde, Yemi Blaq, Sola Sobowale, Ken Erics, Toyin Aimakhu, Segun Arinze, Jibola Dabo, Rotimi Salami, Pa Jimi Solanke, Rachael Okonkwo, Bassey Okon, Lucien Morgan, Magdalena Korpas",
      "country": "",
      "date_added": "September 6, 2021",
      "release_year": 2020,
      "rating": "TV-MA",
      "duration": "117 min",
      "listed_in": "Dramas, International Movies, Thrillers",
      "description": "A family faces destruction in a long-running conflict between communities that pits relatives against each other amid attacks and reprisals."
    },
    {
      "show_id": "s105",
      "type": "TV Show",
      "title": "Tayo the Little Bus",
      "director": "",
      "cast": "Robyn Slade, Kami Desilets",
      "country": "South Korea",
      "date_added": "September 6, 2021",
      "release_year": 2016,
      "rating": "TV-Y",
      "duration": "2 Seasons",
      "listed_in": "Kids' TV, Korean TV Shows",
      "description": "As they learn their routes around the busy city, Tayo and his little bus friends discover new sights and go on exciting adventures every day."
    },
    {
      "show_id": "s106",
      "type": "Movie",
      "title": "Angamaly Diaries",
      "director": "Lijo Jose Pellissery",
      "cast": "Antony Varghese, Reshma Rajan, Binny Rinky Benjamin, Vineeth Vishwam, Kichu Tellus, Sreekanth Dasan, Sarath Kumar, Tito Wilson, Anandhu, Bitto Davis, Sinoj Varghese",
      "country": "India",
      "date_added": "September 5, 2021",
      "release_year": 2017,
      "rating": "TV-14",
      "duration": "128 min",
      "listed_in": "Action & Adventure, Comedies, Dramas",
      "description": "After growing up amidst the gang wars of his hometown, Vincent forms an entrepreneurial squad of his own and ends up on the wrong side of the law."
    },
    {
      "show_id": "s107",
      "type": "TV Show",
      "title": "Bunk'd",
      "director": "",
      "cast": "Peyton List, Karan Brar, Skai Jackson, Miranda May, Kevin G. Quinn, Nathan Arenas, Nina Lu",
      "country": "United States",
      "date_added": "September 5, 2021",
      "release_year": 2021,
      "rating": "TV-G",
      "duration": "5 Seasons",
      "listed_in": "Kids' TV, TV Comedies",
      "description": "The Ross siblings of Disney's hit series \"Jessie\" spend a summer full of fun and adventure at Maine's Camp Kikiwaka, where their parents first met."
    },
    {
      "show_id": "s108",
      "type": "Movie",
      "title": "A Champion Heart",
      "director": "David de Vos",
      "cast": "Mandy Grace, David de Vos, Donna Rusch, Devan Key, Isabella Mancuso, Ariana Guido",
      "country": "United States",
      "date_added": "September 4, 2021",
      "release_year": 2018,
      "rating": "G",
      "duration": "90 min",
      "listed_in": "Children & Family Movies, Dramas",
      "description": "When a grieving teen must work off her debt to a ranch, she cares for a wounded horse that teaches her more about healing than she expected."
    },
    {
      "show_id": "s109",
      "type": "TV Show",
      "title": "Dive Club",
      "director": "",
      "cast": "Aubri Ibrag, Sana'a Shaik, Miah Madden, Mercy Cornwall, Georgia-May Davis, Ryan Harrison, Josh Heuston, Alexander Grant",
      "country": "Australia",
      "date_added": "September 3, 2021",
      "release_year": 2021,
      "rating": "TV-G",
      "duration": "1 Season",
      "listed_in": "Kids' TV, TV Dramas, Teen TV Shows",
      "description": "On the shores of Cape Mercy, a skillful group of teen divers investigate a series of secrets and signs after one of their own mysteriously goes missing."
    },
    {
      "show_id": "s110",
      "type": "TV Show",
      "title": "La casa de papel",
      "director": "",
      "cast": "Úrsula Corberó, Itziar Ituño, Álvaro Morte, Paco Tous, Enrique Arce, Pedro Alonso, María Pedraza, Alba Flores, Miguel Herrán, Jaime Lorente, Esther Acebo, Darko Peric, Kiti Mánver",
      "country": "Spain",
      "date_added": "September 3, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "5 Seasons",
      "listed_in": "Crime TV Shows, International TV Shows, Spanish-Language TV Shows",
      "description": "Eight thieves take hostages and lock themselves in the Royal Mint of Spain as a criminal mastermind manipulates the police to carry out his plan."
    },
    {
      "show_id": "s111",
      "type": "TV Show",
      "title": "Money Heist: From Tokyo to Berlin",
      "director": "Luis Alfaro, Javier Gómez Santander",
      "cast": "",
      "country": "",
      "date_added": "September 3, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "Docuseries, International TV Shows, Spanish-Language TV Shows",
      "description": "The filmmakers and actors behind \"Money Heist\" characters like Tokyo and the Professor talk about the emotional artistic process of filming the series."
    },
    {
      "show_id": "s112",
      "type": "TV Show",
      "title": "Sharkdog",
      "director": "",
      "cast": "Liam Mitchell, Dee Bradley Baker, Grey Griffin, Josh McDermitt, Kari Wahlgren, Judy Alice Lee, Ali Mawji",
      "country": "United States, Singapore",
      "date_added": "September 3, 2021",
      "release_year": 2021,
      "rating": "TV-Y",
      "duration": "1 Season",
      "listed_in": "Kids' TV",
      "description": "Half shark, half dog with a big heart and a belly full of fish sticks! Together, Sharkdog and his human pal Max can take on any silly or messy adventure."
    },
    {
      "show_id": "s113",
      "type": "Movie",
      "title": "Worth",
      "director": "Sara Colangelo",
      "cast": "Michael Keaton, Stanley Tucci, Amy Ryan, Shunori Ramanathan, Ato Blankson-Wood, Tate Donovan, Laura Benanti, Chris Tardio",
      "country": "",
      "date_added": "September 3, 2021",
      "release_year": 2021,
      "rating": "PG-13",
      "duration": "119 min",
      "listed_in": "Dramas",
      "description": "In the wake of the Sept. 11 attacks, a lawyer faces an emotional reckoning as he attempts to put a dollar value on the lives lost. Based on real events."
    },
    {
      "show_id": "s114",
      "type": "Movie",
      "title": "Afterlife of the Party",
      "director": "Stephen Herek",
      "cast": "Victoria Justice, Midori Francis, Robyn Scott, Adam Garcia, Timothy Renouf, Gloria Garcia, Myfanwy Waring, Spencer Sutherland",
      "country": "",
      "date_added": "September 2, 2021",
      "release_year": 2021,
      "rating": "TV-PG",
      "duration": "110 min",
      "listed_in": "Comedies, Romantic Movies",
      "description": "Cassie lives to party... until she dies in a freak accident. Now this social butterfly needs to right her wrongs on Earth if she wants to earn her wings."
    },
    {
      "show_id": "s115",
      "type": "Movie",
      "title": "Anjaam",
      "director": "Rahul Rawail",
      "cast": "Madhuri Dixit, Shah Rukh Khan, Tinnu Anand, Johny Lever, Kalpana Iyer, Himani Shivpuri, Sudha Chandran, Beena, Kiran Kumar",
      "country": "India",
      "date_added": "September 2, 2021",
      "release_year": 1994,
      "rating": "TV-14",
      "duration": "143 min",
      "listed_in": "Dramas, International Movies, Thrillers",
      "description": "A wealthy industrialist’s dangerous obsession with a flight attendant destroys her world, until she takes matters into her own hands to exact revenge."
    },
    {
      "show_id": "s116",
      "type": "Movie",
      "title": "Bright Star",
      "director": "Jane Campion",
      "cast": "Abbie Cornish, Ben Whishaw, Paul Schneider, Kerry Fox, Edie Martin, Thomas Brodie-Sangster, Claudie Blakley, Gerard Monaco, Antonia Campbell-Hughes, Samuel Roukin",
      "country": "United Kingdom, Australia, France",
      "date_added": "September 2, 2021",
      "release_year": 2009,
      "rating": "PG",
      "duration": "119 min",
      "listed_in": "Dramas, Romantic Movies",
      "description": "This drama details the passionate three-year romance between Romantic poet John Keats – who died tragically at age 25 – and his great love and muse."
    },
    {
      "show_id": "s117",
      "type": "Movie",
      "title": "Dhanak",
      "director": "Nagesh Kukunoor",
      "cast": "Krrish Chhabria, Hetal Gada, Vipin Sharma, Gulfam Khan, Suresh Menon, Vijay Maurya, Rajiv Lakshman, Ninad Kamat",
      "country": "India",
      "date_added": "September 2, 2021",
      "release_year": 2015,
      "rating": "TV-PG",
      "duration": "114 min",
      "listed_in": "Comedies, Dramas, Independent Movies",
      "description": "A movie-loving 10-year-old and her blind little brother trek to meet Indian superstar Shah Rukh Khan for help in getting the boy an eye operation."
    },
    {
      "show_id": "s118",
      "type": "Movie",
      "title": "Final Account",
      "director": "Luke Holland",
      "cast": "",
      "country": "United Kingdom, United States",
      "date_added": "September 2, 2021",
      "release_year": 2021,
      "rating": "PG-13",
      "duration": "94 min",
      "listed_in": "Documentaries",
      "description": "This documentary stitches together never-before-seen interviews with the last living generation of people who participated in Hitler's Third Reich."
    },
    {
      "show_id": "s119",
      "type": "Movie",
      "title": "Gurgaon",
      "director": "Shanker Raman",
      "cast": "Akshay Oberoi, Pankaj Tripathi, Ragini Khanna, Aamir Bashir, Shalini Vatsa, Ashish Verma",
      "country": "India",
      "date_added": "September 2, 2021",
      "release_year": 2017,
      "rating": "TV-14",
      "duration": "106 min",
      "listed_in": "Dramas, International Movies, Thrillers",
      "description": "When the daughter of a wealthy family returns from college, she gets a frosty welcome from her brother, who has problems – and plans – of his own."
    },
    {
      "show_id": "s120",
      "type": "Movie",
      "title": "Here and There",
      "director": "JP Habac",
      "cast": "Janine Gutierrez, JC Santos, Victor Anastacio, Yesh Burce, Lotlot De Leon",
      "country": "",
      "date_added": "September 2, 2021",
      "release_year": 2020,
      "rating": "TV-MA",
      "duration": "99 min",
      "listed_in": "Dramas, International Movies, Romantic Movies",
      "description": "After meeting through a heated exchange on social media, two people with different backgrounds begin an online romance in the midst of a pandemic."
    },
    {
      "show_id": "s121",
      "type": "TV Show",
      "title": "Heroes of Goo Jit Zu",
      "director": "",
      "cast": "Jon Allen, Kellen Goff, Joe Hernandez, Kaiji Tang",
      "country": "Australia",
      "date_added": "September 2, 2021",
      "release_year": 2021,
      "rating": "TV-Y7",
      "duration": "1 Season",
      "listed_in": "Kids' TV, TV Comedies",
      "description": "After a meteor crash, a group of zoo animals transforms into squishy, gooey and stretchy superheroes with special powers and soon takes on evildoers."
    },
    {
      "show_id": "s122",
      "type": "TV Show",
      "title": "Hotel Del Luna",
      "director": "",
      "cast": "Lee Ji-eun, Yeo Jin-goo, Shin Jung-geun, Seo Yi-sook, Bae Hae-sun, Pyo Ji-hoon, Cho Hyun-chul, Kang Hong-suk, Lee Do-hyun, Lee Tae-seon, Kang Mina, Park You-na, Oh Ji-ho",
      "country": "",
      "date_added": "September 2, 2021",
      "release_year": 2019,
      "rating": "TV-14",
      "duration": "1 Season",
      "listed_in": "International TV Shows, Romantic TV Shows, TV Comedies",
      "description": "When he's invited to manage a hotel for dead souls, an elite hotelier gets to know the establishment's ancient owner and her strange world."
    },
    {
      "show_id": "s123",
      "type": "Movie",
      "title": "In the Cut",
      "director": "Jane Campion",
      "cast": "Meg Ryan, Mark Ruffalo, Jennifer Jason Leigh, Nick Damici, Sharrieff Pugh, Kevin Bacon, Yaani King Mondschein, Heather Litteer",
      "country": "United Kingdom, Australia, France, United States",
      "date_added": "September 2, 2021",
      "release_year": 2003,
      "rating": "R",
      "duration": "118 min",
      "listed_in": "Thrillers",
      "description": "After embarking on an affair with the cop probing the murder of a young woman, an insular schoolteacher suspects her lover was involved in the crime."
    },
    {
      "show_id": "s124",
      "type": "TV Show",
      "title": "Luv Kushh",
      "director": "",
      "cast": "",
      "country": "",
      "date_added": "September 2, 2021",
      "release_year": 2012,
      "rating": "TV-Y7",
      "duration": "1 Season",
      "listed_in": "Kids' TV",
      "description": "Based on the last book of the epic Ramayana, this series follows the endeavors and adventures of Lord Rama’s twin sons through their childhood."
    },
    {
      "show_id": "s125",
      "type": "TV Show",
      "title": "Pororo - The Little Penguin",
      "director": "",
      "cast": "",
      "country": "South Korea",
      "date_added": "September 2, 2021",
      "release_year": 2013,
      "rating": "TV-Y7",
      "duration": "3 Seasons",
      "listed_in": "Kids' TV, Korean TV Shows",
      "description": "On a tiny island, Pororo the penguin has fun adventures with his friends Eddy the fox, Loopy the beaver, Poby the polar bear and Crong the dinosaur."
    },
    {
      "show_id": "s126",
      "type": "TV Show",
      "title": "Q-Force",
      "director": "",
      "cast": "Sean Hayes, Wanda Sykes, Laurie Metcalf, David Harbour, Gary Cole, Patti Harrison, Matt Rogers",
      "country": "United States",
      "date_added": "September 2, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "Crime TV Shows, TV Action & Adventure, TV Comedies",
      "description": "A gay superspy and his scrappy LGBTQ squad fight to prove themselves to the agency that underestimated them. Today, West Hollywood… tomorrow, the world!"
    },
    {
      "show_id": "s127",
      "type": "Movie",
      "title": "Shikara",
      "director": "Vidhu Vinod Chopra",
      "cast": "Aadil Khan, Sadia Khateeb, Zain Khan Durrani, Priyanshu Chatterjee, Bhavna Chauhan, Ashwin Dhar, Farid Azad Khan, Saghar Sehrai",
      "country": "India",
      "date_added": "September 2, 2021",
      "release_year": 2020,
      "rating": "TV-14",
      "duration": "115 min",
      "listed_in": "Dramas, International Movies, Romantic Movies",
      "description": "A couple must strive to remain resilient after regional hostilities drive them from their beloved home into a refugee camp."
    },
    {
      "show_id": "s128",
      "type": "Movie",
      "title": "A Cinderella Story",
      "director": "Mark Rosman",
      "cast": "Hilary Duff, Chad Michael Murray, Jennifer Coolidge, Dan Byrd, Regina King, Julie Gonzalo, Lin Shaye, Madeline Zima, Andrea Avery, Mary Pat Gleason, Paul Rodriguez, Whip Hubley, Kevin Kilner, Erica Hubbard, Simon Helberg",
      "country": "United States, Canada",
      "date_added": "September 1, 2021",
      "release_year": 2004,
      "rating": "PG",
      "duration": "95 min",
      "listed_in": "Children & Family Movies, Comedies",
      "description": "Teen Sam meets the boy of her dreams at a dance before returning to toil in her stepmother's diner. Can her lost cell phone bring them together?"
    },
    {
      "show_id": "s129",
      "type": "Movie",
      "title": "Agatha Christie's Crooked House",
      "director": "Gilles Paquet-Brenner",
      "cast": "Glenn Close, Terence Stamp, Max Irons, Gillian Anderson, Christina Hendricks, Stefanie Martini, Julian Sands, Honor Kneafsey, Christian McKay, Amanda Abbington",
      "country": "",
      "date_added": "September 1, 2021",
      "release_year": 2017,
      "rating": "PG-13",
      "duration": "115 min",
      "listed_in": "Dramas, International Movies, Thrillers",
      "description": "When a detective investigates the death of his ex-lover's grandfather, he uncovers secrets about the tycoon's manipulative family."
    },
    {
      "show_id": "s130",
      "type": "Movie",
      "title": "An Unfinished Life",
      "director": "Lasse Hallström",
      "cast": "Robert Redford, Jennifer Lopez, Morgan Freeman, Josh Lucas, Damian Lewis, Camryn Manheim, Becca Gardner, Lynda Boyd, Rob Hayter, P. Lynn Johnson",
      "country": "Germany, United States",
      "date_added": "September 1, 2021",
      "release_year": 2005,
      "rating": "PG-13",
      "duration": "108 min",
      "listed_in": "Dramas",
      "description": "A grieving widow and her daughter move in with her estranged father-in-law in Wyoming, where time allows them to heal and forgive."
    },
    {
      "show_id": "s131",
      "type": "Movie",
      "title": "Barbie Big City Big Dreams",
      "director": "Scott Pleydell-Pearce",
      "cast": "America Young, Amber May, Giselle Fernandez, Alejandro Saab, Dinora Walcott",
      "country": "",
      "date_added": "September 1, 2021",
      "release_year": 2021,
      "rating": "TV-Y",
      "duration": "63 min",
      "listed_in": "Children & Family Movies, Music & Musicals",
      "description": "At a summer performing arts program in New York City, Barbie from Malibu meets Barbie from Brooklyn, and the two become fast friends."
    },
    {
      "show_id": "s132",
      "type": "Movie",
      "title": "Blade Runner: The Final Cut",
      "director": "Ridley Scott",
      "cast": "Harrison Ford, Rutger Hauer, Sean Young, Edward James Olmos, M. Emmet Walsh, Daryl Hannah, William Sanderson, Brion James, Joe Turkel, Joanna Cassidy, James Hong, Morgan Paull",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 1982,
      "rating": "R",
      "duration": "117 min",
      "listed_in": "Action & Adventure, Classic Movies, Cult Movies",
      "description": "In a smog-choked dystopian Los Angeles, blade runner Rick Deckard is called out of retirement to snuff a quartet of escaped \"replicants.\""
    },
    {
      "show_id": "s133",
      "type": "TV Show",
      "title": "Brave Animated Series",
      "director": "",
      "cast": "Tseng Yun-fan, Kao Yun-shuo, Chiang Ching-yen, Meng Ching-fu, Huang Bai-wei, Ma Kuo-yao, Chen Yen-chun, Sun Ke-fang, Kai Yang-niu, Chen Yu-wen, Nick Liao, Lin Kai-ling, Mickey Huang, Liu Kuan-ting, Jiang Du-hui",
      "country": "",
      "date_added": "September 1, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "International TV Shows, TV Action & Adventure, TV Comedies",
      "description": "A group of superheroes sets out to rid the world of evil — only to realize they may not be standing on the side of justice. Based on a popular comic."
    },
    {
      "show_id": "s134",
      "type": "Movie",
      "title": "Chappie",
      "director": "Neill Blomkamp",
      "cast": "Sharlto Copley, Hugh Jackman, Sigourney Weaver, Dev Patel, Ninja, Yo-Landi Visser, Jose Pablo Cantillo, Brandon Auret, Johnny Selema, Maurice Carpede",
      "country": "South Africa, United States",
      "date_added": "September 1, 2021",
      "release_year": 2015,
      "rating": "R",
      "duration": "121 min",
      "listed_in": "Action & Adventure, Sci-Fi & Fantasy",
      "description": "In a futuristic society where an indestructible robot police force keeps crime at bay, a lone droid evolves to the next level of artificial intelligence."
    },
    {
      "show_id": "s135",
      "type": "Movie",
      "title": "Clear and Present Danger",
      "director": "Phillip Noyce",
      "cast": "Harrison Ford, Willem Dafoe, Anne Archer, Joaquim de Almeida, Henry Czerny, Harris Yulin, Donald Moffat, Miguel Sandoval, Benjamin Bratt, Dean Jones, Thora Birch, James Earl Jones, Raymond Cruz",
      "country": "United States, Mexico",
      "date_added": "September 1, 2021",
      "release_year": 1994,
      "rating": "PG-13",
      "duration": "142 min",
      "listed_in": "Action & Adventure, Dramas",
      "description": "When the president's friend is murdered, CIA Deputy Director Jack Ryan becomes unwittingly involved in an illegal war against a Colombian drug cartel."
    },
    {
      "show_id": "s136",
      "type": "Movie",
      "title": "Cliffhanger",
      "director": "Renny Harlin",
      "cast": "Sylvester Stallone, John Lithgow, Michael Rooker, Janine Turner, Rex Linn, Caroline Goodall, Leon, Craig Fairbrass, Ralph Waite, Max Perlich, Paul Winfield",
      "country": "United States, Italy, France, Japan",
      "date_added": "September 1, 2021",
      "release_year": 1993,
      "rating": "R",
      "duration": "113 min",
      "listed_in": "Action & Adventure",
      "description": "Ranger Gabe Walker and his partner are called to rescue a group of stranded climbers, only to learn the climbers are actually thieving hijackers."
    },
    {
      "show_id": "s137",
      "type": "Movie",
      "title": "Cold Mountain",
      "director": "Anthony Minghella",
      "cast": "Jude Law, Nicole Kidman, Renée Zellweger, Eileen Atkins, Brendan Gleeson, Philip Seymour Hoffman, Natalie Portman, Giovanni Ribisi, Donald Sutherland, Ray Winstone",
      "country": "United States, Italy, Romania, United Kingdom",
      "date_added": "September 1, 2021",
      "release_year": 2003,
      "rating": "R",
      "duration": "154 min",
      "listed_in": "Dramas, Romantic Movies",
      "description": "This drama follows a wounded Civil War soldier making the long journey home, while his faraway love fights for survival on her deceased father's farm."
    },
    {
      "show_id": "s138",
      "type": "Movie",
      "title": "Crocodile Dundee in Los Angeles",
      "director": "Simon Wincer",
      "cast": "Paul Hogan, Linda Kozlowski, Jere Burns, Jonathan Banks, Aida Turturro, Alec Wilson, Gerry Skilton, Steve Rackman, Serge Cockburn, Paul Rodriguez, Mark Adair-Rios, Tiriel Mora, Grant Piro, Mike Tyson",
      "country": "Australia, United States",
      "date_added": "September 1, 2021",
      "release_year": 2001,
      "rating": "PG",
      "duration": "95 min",
      "listed_in": "Action & Adventure, Comedies",
      "description": "When Mick \"Crocodile\" Dundee and his family land in Los Angeles, they soon learn some lessons about American life in this comedy sequel."
    },
    {
      "show_id": "s139",
      "type": "Movie",
      "title": "Dear John",
      "director": "Lasse Hallström",
      "cast": "Channing Tatum, Amanda Seyfried, Richard Jenkins, Henry Thomas, D.J. Cotrona, Cullen Moss, Gavin McCulley, Jose Lucena Jr., Keith Robinson, Scott Porter",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 2010,
      "rating": "PG-13",
      "duration": "108 min",
      "listed_in": "Dramas, Romantic Movies",
      "description": "While on summer leave, a U.S. soldier falls for a college student. But when he's forced to reenlist, their handwritten letters hold the lovers together."
    },
    {
      "show_id": "s140",
      "type": "Movie",
      "title": "Do the Right Thing",
      "director": "Spike Lee",
      "cast": "Danny Aiello, Ossie Davis, Ruby Dee, Richard Edson, Giancarlo Esposito, Spike Lee, Bill Nunn, John Turturro, Paul Benjamin, Frankie Faison, Samuel L. Jackson, Rosie Perez, Martin Lawrence, Miguel Sandoval",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 1989,
      "rating": "R",
      "duration": "120 min",
      "listed_in": "Classic Movies, Comedies, Dramas",
      "description": "On a sweltering day in Brooklyn, simmering racial tensions between residents rise to the surface and ignite rage, violence and tragedy."
    },
    {
      "show_id": "s141",
      "type": "Movie",
      "title": "El patrón, radiografía de un crimen",
      "director": "Sebastián Schindel",
      "cast": "Joaquín Furriel, Luis Ziembrowski, Guillermo Pfening, Mónica Lairana, Germán de Silva, Victoria Raposo, Andrea Garrote",
      "country": "Argentina, Venezuela",
      "date_added": "September 1, 2021",
      "release_year": 2014,
      "rating": "TV-MA",
      "duration": "100 min",
      "listed_in": "Dramas, International Movies, Thrillers",
      "description": "A lawyer defends an illiterate man whose exploitation by a cruel boss while working as a butcher in Buenos Aires led to tragedy. Based on a true case."
    },
    {
      "show_id": "s142",
      "type": "Movie",
      "title": "Extraction",
      "director": "Steven C. Miller",
      "cast": "Bruce Willis, Kellan Lutz, Gina Carano, D.B. Sweeney, Joshua Mikel, Steve Coulter, Dan Bilzerian, Heather Johansen",
      "country": "United States, United Kingdom, Canada",
      "date_added": "September 1, 2021",
      "release_year": 2015,
      "rating": "R",
      "duration": "82 min",
      "listed_in": "Action & Adventure",
      "description": "When a retired CIA agent is kidnapped, his son, a government analyst, embarks on an unauthorized mission to find him and halt a terrorist plot."
    },
    {
      "show_id": "s143",
      "type": "Movie",
      "title": "Freedom Writers",
      "director": "Richard LaGravenese",
      "cast": "Hilary Swank, Patrick Dempsey, Scott Glenn, Imelda Staunton, April L. Hernandez, Mario, Kristin Herrera, Jaclyn Ngan, Sergio Montalvo, Jason Finn, Deance Wyatt, Vanetta Smith",
      "country": "Germany, United States",
      "date_added": "September 1, 2021",
      "release_year": 2007,
      "rating": "PG-13",
      "duration": "124 min",
      "listed_in": "Dramas",
      "description": "While her at-risk students are reading classics such as \"The Diary of Anne Frank,\" a teacher asks them to keep journals about their troubled lives."
    },
    {
      "show_id": "s144",
      "type": "Movie",
      "title": "Green Lantern",
      "director": "Martin Campbell",
      "cast": "Ryan Reynolds, Blake Lively, Peter Sarsgaard, Mark Strong, Tim Robbins, Jay O. Sanders, Taika Waititi, Angela Bassett",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 2011,
      "rating": "PG-13",
      "duration": "114 min",
      "listed_in": "Action & Adventure, Sci-Fi & Fantasy",
      "description": "Test pilot Hal Jordan harnesses glowing new powers for good when he wears an otherworldly ring and helps an intergalactic force stop a powerful threat."
    },
    {
      "show_id": "s145",
      "type": "Movie",
      "title": "House Party",
      "director": "Reginald Hudlin",
      "cast": "Christopher Reid, Christopher Martin, Robin Harris, Tisha Campbell, A.J. Johnson, Martin Lawrence, Paul Anthony, Bowlegged Lou, B-Fine, Edith Fields, Kelly Jo Minter, Clifton Powell, Verda Bridges",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 1990,
      "rating": "R",
      "duration": "104 min",
      "listed_in": "Comedies, Cult Movies",
      "description": "Grounded by his strict father, Kid risks life and limb to go to his best friend Play's big bash but experiences one obstacle after another."
    },
    {
      "show_id": "s146",
      "type": "Movie",
      "title": "House Party 2",
      "director": "George Jackson, Doug McHenry",
      "cast": "Christopher Reid, Christopher Martin, Martin Lawrence, Bowlegged Lou, Paul Anthony, B-Fine, Tisha Campbell, Kamron, Iman, Queen Latifah",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 1991,
      "rating": "R",
      "duration": "94 min",
      "listed_in": "Comedies, Cult Movies, Music & Musicals",
      "description": "Kid goes off to college with scholarship money but when Play loses Kid's tuition funds to a shady music promoter, they devise a wild plan to raise cash."
    },
    {
      "show_id": "s147",
      "type": "Movie",
      "title": "House Party 3",
      "director": "Eric Meza",
      "cast": "Christopher Reid, Christopher Martin, Tisha Campbell, David Edwards, Angela Means, Ketty Lester, Bernie Mac, Michael Colyar, Chris Tucker, Khandi Alexander",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 1994,
      "rating": "R",
      "duration": "94 min",
      "listed_in": "Comedies, Music & Musicals",
      "description": "After Kid gets engaged, Play plans to throw the biggest bachelor party ever. But every celebration for these two always comes with complications."
    },
    {
      "show_id": "s148",
      "type": "TV Show",
      "title": "How to Be a Cowboy",
      "director": "",
      "cast": "",
      "country": "",
      "date_added": "September 1, 2021",
      "release_year": 2021,
      "rating": "TV-PG",
      "duration": "1 Season",
      "listed_in": "Reality TV",
      "description": "Dale Brisby uses social media savvy and rodeo skills to keep cowboy traditions alive — and now he's teaching the world how to cowboy right, ol' son."
    },
    {
      "show_id": "s149",
      "type": "TV Show",
      "title": "HQ Barbers",
      "director": "Gerhard Mostert",
      "cast": "Hakeem Kae-Kazim, Chioma Omeruah, Orukotan Adejola, Flora Chiedo, Emeka Nwagbaraocha, Anthony Oseyemi, Oluwabukola Thomas, Soibifaa Dokubo",
      "country": "",
      "date_added": "September 1, 2021",
      "release_year": 2020,
      "rating": "TV-14",
      "duration": "1 Season",
      "listed_in": "TV Shows",
      "description": "When a family run barber shop in the heart of Lagos is threatened by real estate developers, they'll do whatever it takes to stay in business."
    },
    {
      "show_id": "s150",
      "type": "Movie",
      "title": "I Got the Hook Up",
      "director": "Michael Martin",
      "cast": "Master P, Anthony Johnson, Gretchen Palmer, Frantz Turner, Richard Keats, Joe Estevez, William Knight, Anthony Boswell, Tommy 'Tiny' Lister, Helen Martin, John Witherspoon, Mia X",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 1998,
      "rating": "R",
      "duration": "93 min",
      "listed_in": "Action & Adventure, Comedies",
      "description": "After getting their hands on a misdirected shipment of cell phones, two hustlers try to cash in by hawking the merchandise from the back of their van."
    },
    {
      "show_id": "s151",
      "type": "Movie",
      "title": "In Too Deep",
      "director": "Michael Rymer",
      "cast": "Omar Epps, LL Cool J, Nia Long, Stanley Tucci, Pam Grier, Hill Harper, Jake Weber, David Patrick Kelly, Veronica Webb, Ron Canada, Robert LaSardo, Gano Grills, Ivonne Coll, Don Harvey, Mya, Nasir 'Nas' Jones, Jermaine Dupri",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 1999,
      "rating": "R",
      "duration": "97 min",
      "listed_in": "Thrillers",
      "description": "Rookie cop Jeffrey Cole poses as a drug dealer to take down a crime lord and soon gets caught up in an underworld of bribery, intimidation and murder."
    },
    {
      "show_id": "s152",
      "type": "Movie",
      "title": "Initial D",
      "director": "Andrew Lau Wai-keung, Alan Mak",
      "cast": "Jay Chou, Anne Suzuki, Edison Chen, Anthony Wong Chau-sang, Shawn Yue, Chapman To, Jordan Chan, Kenny Bee",
      "country": "China, Hong Kong",
      "date_added": "September 1, 2021",
      "release_year": 2005,
      "rating": "TV-14",
      "duration": "109 min",
      "listed_in": "Action & Adventure, International Movies",
      "description": "By day, an 18-year-old delivers tofu for his father, a retired race car driver; but by night, it's the teen's turn to take the wheel."
    },
    {
      "show_id": "s153",
      "type": "Movie",
      "title": "Janoskians: Untold and Untrue",
      "director": "Brett Weiner",
      "cast": "Jai Brooks, Luke Brooks, James Yammouni, Daniel Sahyounie, Beau Brooks",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 2016,
      "rating": "TV-MA",
      "duration": "88 min",
      "listed_in": "Comedies",
      "description": "Follow the story of three Australian brothers and their two friends who became an international sensation by posting pranks and gags on YouTube."
    },
    {
      "show_id": "s154",
      "type": "TV Show",
      "title": "Kid-E-Cats",
      "director": "",
      "cast": "Lori Gardner, Kate Bristol, Billy Bob Thompson, Marc Thompson, Erica Schroeder",
      "country": "Russia",
      "date_added": "September 1, 2021",
      "release_year": 2016,
      "rating": "TV-Y",
      "duration": "2 Seasons",
      "listed_in": "Kids' TV",
      "description": "Cookie, Pudding and Candy are kitten siblings whose favorite things are sweet treats and letting their curiosity lead them on adventures in learning."
    },
    {
      "show_id": "s155",
      "type": "TV Show",
      "title": "Kuroko's Basketball",
      "director": "",
      "cast": "Kensho Ono, Yuki Ono, Chiwa Saito, Yoshimasa Hosoya, Hirofumi Nojima, Kenji Hamada, Takuya Eguchi, Soichiro Hoshi, Tatsuhisa Suzuki, Go Inoue, Daisuke Ono, Ryohei Kimura, Junichi Suwabe, Kazuya Nakai, Fumiko Orikasa, Kenichi Suzumura, Kisho Taniyama, Hiroshi Kamiya",
      "country": "Japan",
      "date_added": "September 1, 2021",
      "release_year": 2015,
      "rating": "TV-MA",
      "duration": "3 Seasons",
      "listed_in": "Anime Series, International TV Shows, Teen TV Shows",
      "description": "Five middle school basketball stars went to separate high schools, and now Tetsuya Kuroko and Seirin High are making their play for glory."
    },
    {
      "show_id": "s156",
      "type": "Movie",
      "title": "Labyrinth",
      "director": "Jim Henson",
      "cast": "David Bowie, Jennifer Connelly, Frank Oz, Kevin Clash, Anthony Asbury, Dave Goelz, Brian Henson, Ron Mueck, Karen Prell, Shari Weiser",
      "country": "United Kingdom, United States",
      "date_added": "September 1, 2021",
      "release_year": 1986,
      "rating": "PG",
      "duration": "101 min",
      "listed_in": "Action & Adventure, Children & Family Movies, Cult Movies",
      "description": "In Jim Henson's fantasy, teen Sarah embarks on a life-altering quest to rescue her little brother from the clutches of a treacherous goblin."
    },
    {
      "show_id": "s157",
      "type": "Movie",
      "title": "Letters to Juliet",
      "director": "Gary Winick",
      "cast": "Amanda Seyfried, Christopher Egan, Gael García Bernal, Vanessa Redgrave, Franco Nero, Luisa Ranieri, Marina Massironi, Milena Vukotic, Marcia DeBonis, Luisa De Santis, Lidia Biondi, Giordano Formenti, Chris Egan",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 2010,
      "rating": "PG",
      "duration": "105 min",
      "listed_in": "Comedies, Dramas, Romantic Movies",
      "description": "By responding to a letter addressed to Shakespeare's tragic heroine Juliet Capulet, an American woman in Verona, Italy, is led in search of romance."
    },
    {
      "show_id": "s158",
      "type": "Movie",
      "title": "Level 16",
      "director": "Danishka Esterhazy",
      "cast": "Katie Douglas, Celina Martin, Peter Outerbridge, Sara Canning, Alexis Whelan, Amalia Williamson, Josette Halpert, Kiana Madeira",
      "country": "Canada",
      "date_added": "September 1, 2021",
      "release_year": 2018,
      "rating": "TV-14",
      "duration": "102 min",
      "listed_in": "Sci-Fi & Fantasy, Thrillers",
      "description": "In a bleak academy that teaches girls the virtues of passivity, two students uncover the ghastly purpose behind their training and resolve to escape."
    },
    {
      "show_id": "s159",
      "type": "Movie",
      "title": "Love Don't Cost a Thing",
      "director": "Troy Byer",
      "cast": "Nick Cannon, Christina Milian, Kenan Thompson, Kal Penn, Steve Harvey, Al Thompson, Ashley Monique Clark, Elimu Nelson, Nichole Robinson, Melissa Schuman",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 2003,
      "rating": "PG-13",
      "duration": "101 min",
      "listed_in": "Comedies, Romantic Movies",
      "description": "A nerdy teen tries to make himself cool by association when he convinces a popular cheerleader to pose as his girlfriend."
    },
    {
      "show_id": "s160",
      "type": "Movie",
      "title": "Love in a Puff",
      "director": "Pang Ho-cheung",
      "cast": "Miriam Chin Wah Yeung, Shawn Yue, Singh Hartihan Bitto, Isabel Chan, Cheung Tat-ming, Matt Chow, Chui Tien-you, Queenie Chu, Charmaine Fong, Vincent Kok",
      "country": "Hong Kong",
      "date_added": "September 1, 2021",
      "release_year": 2010,
      "rating": "TV-MA",
      "duration": "103 min",
      "listed_in": "Comedies, Dramas, International Movies",
      "description": "When the Hong Kong government enacts a ban on smoking cigarettes indoors, the new law drives hard-core smokers outside, facilitating unlikely connections."
    },
    {
      "show_id": "s161",
      "type": "TV Show",
      "title": "Major Dad",
      "director": "",
      "cast": "Gerald McRaney, Shanna Reed, Nicole Dubuc, Chelsea Hertford, Marisa Ryan, Matt Mulhern, Beverly Archer, Jon Cypher",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 1992,
      "rating": "TV-PG",
      "duration": "4 Seasons",
      "listed_in": "TV Comedies",
      "description": "When he marries a journalist and becomes stepdad to her daughters, a U.S. Marine finds his once-orderly life no longer entirely under his command."
    },
    {
      "show_id": "s162",
      "type": "Movie",
      "title": "Mars Attacks!",
      "director": "Tim Burton",
      "cast": "Jack Nicholson, Glenn Close, Annette Bening, Pierce Brosnan, Danny DeVito, Martin Short, Sarah Jessica Parker, Michael J. Fox, Rod Steiger, Tom Jones, Lukas Haas, Natalie Portman",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 1996,
      "rating": "PG-13",
      "duration": "106 min",
      "listed_in": "Comedies, Cult Movies, Sci-Fi & Fantasy",
      "description": "As flying saucers head for Earth, the president of the United States prepares to welcome alien visitors but soon learns they're not coming in peace."
    },
    {
      "show_id": "s163",
      "type": "Movie",
      "title": "Marshall",
      "director": "Reginald Hudlin",
      "cast": "Chadwick Boseman, Josh Gad, Kate Hudson, Sterling K. Brown, Dan Stevens, James Cromwell, Keesha Sharp, Roger Guenveur Smith, Derrick Baskin, Barrett Doss",
      "country": "United States, China, Hong Kong",
      "date_added": "September 1, 2021",
      "release_year": 2017,
      "rating": "PG-13",
      "duration": "118 min",
      "listed_in": "Dramas",
      "description": "This biopic of Thurgood Marshall, the first Black U.S. Supreme Court justice, centers on his pivotal work in a sensational case as an NAACP lawyer."
    },
    {
      "show_id": "s164",
      "type": "Movie",
      "title": "My Boss's Daughter",
      "director": "David Zucker",
      "cast": "Ashton Kutcher, Tara Reid, Jeffrey Tambor, Andy Richter, Michael Madsen, Jon Abrahams, David Koechner, Carmen Electra, Kenan Thompson, Terence Stamp, Molly Shannon",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 2003,
      "rating": "R",
      "duration": "86 min",
      "listed_in": "Comedies, Romantic Movies",
      "description": "A young man house-sits for his mean boss, hoping to use it as an opportunity to win the heart of the boss's daughter, on whom he's long had a crush."
    },
    {
      "show_id": "s165",
      "type": "Movie",
      "title": "Mystery Men",
      "director": "Kinka Usher",
      "cast": "Ben Stiller, Hank Azaria, William H. Macy, Janeane Garofalo, Kel Mitchell, Paul Reubens, Wes Studi, Greg Kinnear, Geoffrey Rush, Lena Olin, Eddie Izzard, Artie Lange, Pras, Claire Forlani, Tom Waits",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 1999,
      "rating": "PG-13",
      "duration": "121 min",
      "listed_in": "Action & Adventure, Comedies",
      "description": "A team of far-from-super heroes try to earn respect by springing into action when brave and dashing Captain Amazing disappears."
    },
    {
      "show_id": "s166",
      "type": "TV Show",
      "title": "Oldsters",
      "director": "",
      "cast": "Patricio Contreras, Alejandro Goic, Sergio Hernández, Mariana Loyola Ruz, Alejandro Trejo, Daniel Alcaíno Cuevas, Nicolás Poblete, Susana Hidalgo, Gloria Münchmeyer",
      "country": "",
      "date_added": "September 1, 2021",
      "release_year": 2019,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "Crime TV Shows, International TV Shows, Spanish-Language TV Shows",
      "description": "Three friends in their 70s step out of retirement to become a band of outlaws whose mission is to help those let down by the justice system."
    },
    {
      "show_id": "s167",
      "type": "Movie",
      "title": "Once Upon a Time in America",
      "director": "Sergio Leone",
      "cast": "Robert De Niro, James Woods, Elizabeth McGovern, Treat Williams, Tuesday Weld, Burt Young, Joe Pesci, Danny Aiello, William Forsythe, James Hayden",
      "country": "Italy, United States",
      "date_added": "September 1, 2021",
      "release_year": 1984,
      "rating": "R",
      "duration": "229 min",
      "listed_in": "Classic Movies, Dramas",
      "description": "Director Sergio Leone's sprawling crime epic follows a group of Jewish mobsters who rise in the ranks of organized crime in 1920s New York City."
    },
    {
      "show_id": "s168",
      "type": "Movie",
      "title": "Open Season 2",
      "director": "Matthew O'Callaghan, Todd Wilderman",
      "cast": "Joel McHale, Mike Epps, Jane Krakowski, Billy Connolly, Crispin Glover, Steve Schirripa, Georgia Engel, Diedrich Bader, Cody Cameron, Fred Stoller, Olivia Hack",
      "country": "United States, Canada",
      "date_added": "September 1, 2021",
      "release_year": 2008,
      "rating": "PG",
      "duration": "76 min",
      "listed_in": "Children & Family Movies, Comedies",
      "description": "Elliot the buck and his forest-dwelling cohorts must rescue their dachshund pal from some spoiled pets bent on returning him to domesticity."
    },
    {
      "show_id": "s169",
      "type": "Movie",
      "title": "Osmosis Jones",
      "director": "Bobby Farrelly, Peter Farrelly",
      "cast": "Chris Rock, Laurence Fishburne, David Hyde Pierce, Brandy Norwood, William Shatner, Ron Howard, Kid Rock, Ben Stein",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 2001,
      "rating": "PG",
      "duration": "95 min",
      "listed_in": "Action & Adventure, Children & Family Movies, Comedies",
      "description": "Peter and Bobby Farrelly outdo themselves with this partially animated tale about an out-of-shape 40-year-old man who's the host to various organisms."
    },
    {
      "show_id": "s170",
      "type": "Movie",
      "title": "Poseidon",
      "director": "Wolfgang Petersen",
      "cast": "Josh Lucas, Kurt Russell, Jacinda Barrett, Richard Dreyfuss, Emmy Rossum, Mía Maestro, Mike Vogel, Kevin Dillon, Freddy Rodríguez",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 2006,
      "rating": "PG-13",
      "duration": "98 min",
      "listed_in": "Action & Adventure, Dramas",
      "description": "A tidal wave spells disaster for a ship of New Year's Eve revelers when it capsizes the mammoth vessel, sending passengers into a battle for survival."
    },
    {
      "show_id": "s171",
      "type": "Movie",
      "title": "Rhyme & Reason",
      "director": "Peter Spirer",
      "cast": "Too $hort, B-Real, Kurtis Blow, Da Brat, Grandmaster Caz, Sean \"P. Diddy\" Combs, Chuck D., Desiree Densiti, Dr. Dre, E-40, MC Eiht, Heavy D, Lauryn Hill, Ice-T, Wyclef Jean, Ras Kass, KRS-One, L.V., Mack 10, Craig Mack, Method Man, Keith Murray, Nasir 'Nas' Jones, The Notorious B.I.G., Master P, Q-Tip, Raekwon, Redman, Senen Reyes, Busta Rhymes, RZA, DJ Scratch, Erick Sermon, Tupac Shakur, Adario Strange, Suave",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 1997,
      "rating": "R",
      "duration": "89 min",
      "listed_in": "Documentaries, Music & Musicals",
      "description": "The world and culture of rap song topics such as race, violence, police, family and sex are examined by hip-hop performers from both coasts."
    },
    {
      "show_id": "s172",
      "type": "Movie",
      "title": "Same Kind of Different as Me",
      "director": "Michael Carney",
      "cast": "Greg Kinnear, Renée Zellweger, Djimon Hounsou, Jon Voight, Olivia Holt",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 2017,
      "rating": "PG-13",
      "duration": "120 min",
      "listed_in": "Dramas, Faith & Spirituality",
      "description": "A wealthy couple whose marriage is on the rocks befriends a local homeless man who changes their perspectives in this inspiring true story."
    },
    {
      "show_id": "s173",
      "type": "Movie",
      "title": "School of Rock",
      "director": "Richard Linklater",
      "cast": "Jack Black, Joan Cusack, Mike White, Sarah Silverman, Lee Wilkof, Kate McGregor-Stewart, Adam Pascal, Suzzanne Douglas, Miranda Cosgrove, Kevin Alexander Clark, Joey Gaydos Jr., Robert Tsai, Veronica Afflerbach, Jordan-Claire Green",
      "country": "United States, Germany",
      "date_added": "September 1, 2021",
      "release_year": 2003,
      "rating": "PG-13",
      "duration": "110 min",
      "listed_in": "Comedies, Music & Musicals",
      "description": "Musician Dewey Finn gets a job as a fourth-grade substitute teacher, where he secretly begins teaching his students the finer points of rock 'n' roll."
    },
    {
      "show_id": "s174",
      "type": "Movie",
      "title": "Snervous Tyler Oakley",
      "director": "Amy Rice",
      "cast": "Tyler Oakley",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 2015,
      "rating": "PG-13",
      "duration": "83 min",
      "listed_in": "Documentaries, LGBTQ Movies",
      "description": "The inspiring Internet star and LGBT advocate shares an intimate view of his life and relationships during his international \"Slumber Party\" tour."
    },
    {
      "show_id": "s175",
      "type": "Movie",
      "title": "Tears of the Sun",
      "director": "Antoine Fuqua",
      "cast": "Bruce Willis, Monica Bellucci, Cole Hauser, Eamonn Walker, Johnny Messner, Nick Chinlund, Charles Ingram, Paul Francis, Chad Smith, Tom Skerritt, Malick Bowens, Awaovieyi Agie",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 2003,
      "rating": "R",
      "duration": "121 min",
      "listed_in": "Action & Adventure, Dramas",
      "description": "A Navy SEAL is sent to a war-torn African jungle to rescue a doctor, only to realize he must also save the refugees in the physician's care."
    },
    {
      "show_id": "s176",
      "type": "Movie",
      "title": "The Blue Lagoon",
      "director": "Randal Kleiser",
      "cast": "Brooke Shields, Christopher Atkins, Leo McKern, William Daniels, Elva Josephson, Glenn Kohan, Alan Hopgood, Gus Mercurio",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 1980,
      "rating": "R",
      "duration": "105 min",
      "listed_in": "Dramas, Romantic Movies",
      "description": "Two shipwrecked children, stranded for years on a deserted island, fall in love as teenagers and attempt to forge a life in the isolated paradise."
    },
    {
      "show_id": "s177",
      "type": "Movie",
      "title": "The Golden Child",
      "director": "Michael Ritchie",
      "cast": "Eddie Murphy, J.L. Reate, Charles Dance, Charlotte Lewis, Victor Wong, Randall Tex Cobb, James Hong, Shakti Chen, Tau Logo, Tiger Chung Lee",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 1986,
      "rating": "PG-13",
      "duration": "94 min",
      "listed_in": "Action & Adventure, Comedies",
      "description": "A fast-talking L.A. social worker goes through a series of traps and terrors to find a kidnapped Tibetan child with mystical powers."
    },
    {
      "show_id": "s178",
      "type": "Movie",
      "title": "The Guns of Navarone",
      "director": "J. Lee Thompson",
      "cast": "Gregory Peck, David Niven, Anthony Quinn, Stanley Baker, Anthony Quayle, James Darren, Irene Papas, Gia Scala, James Robertson Justice, Richard Harris",
      "country": "United Kingdom, United States",
      "date_added": "September 1, 2021",
      "release_year": 1961,
      "rating": "TV-14",
      "duration": "156 min",
      "listed_in": "Action & Adventure, Classic Movies",
      "description": "During World War II, British forces launch an attack designed to take out the massive Nazi cannons that guard a critical sea channel."
    },
    {
      "show_id": "s179",
      "type": "Movie",
      "title": "The Interview",
      "director": "Evan Goldberg, Seth Rogen",
      "cast": "James Franco, Seth Rogen, Lizzy Caplan, Randall Park, Diana Bang, Timothy Simons, Reese Alexander, James Yi",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 2014,
      "rating": "R",
      "duration": "112 min",
      "listed_in": "Action & Adventure, Comedies",
      "description": "Seth Rogen and James Franco star in this provocative comedy about two journalists recruited by the CIA after they arrange an interview with Kim Jong-un."
    },
    {
      "show_id": "s180",
      "type": "Movie",
      "title": "The Nutty Professor",
      "director": "Tom Shadyac",
      "cast": "Eddie Murphy, Jada Pinkett Smith, James Coburn, Larry Miller, Dave Chappelle, John Ales, Patricia Wilson, Jamal Mixon",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 1996,
      "rating": "PG-13",
      "duration": "95 min",
      "listed_in": "Comedies, Romantic Movies",
      "description": "After being made fun of for his weight, a kind and brainy professor takes a dose of a revolutionary formula that changes more than just his appearance."
    },
    {
      "show_id": "s181",
      "type": "Movie",
      "title": "The Nutty Professor II: The Klumps",
      "director": "Peter Segal",
      "cast": "Eddie Murphy, Janet Jackson, Larry Miller, John Ales, Richard Gant, Anna Maria Horsford, Melinda McGraw, Jamal Mixon, Gabriel Williams, Chris Elliott",
      "country": "",
      "date_added": "September 1, 2021",
      "release_year": 2000,
      "rating": "PG-13",
      "duration": "107 min",
      "listed_in": "Comedies, Romantic Movies",
      "description": "After getting engaged, Sherman Klump prepares for his big day. But his sinister alter ego Buddy Love threatens to ruin his wedding and reputation."
    },
    {
      "show_id": "s183",
      "type": "Movie",
      "title": "Welcome Home Roscoe Jenkins",
      "director": "Malcolm D. Lee",
      "cast": "Martin Lawrence, James Earl Jones, Joy Bryant, Margaret Avery, Mike Epps, Mo'Nique, Cedric the Entertainer, Nicole Ari Parker, Michael Clarke Duncan, Louis C.K.",
      "country": "United States",
      "date_added": "September 1, 2021",
      "release_year": 2008,
      "rating": "PG-13",
      "duration": "114 min",
      "listed_in": "Comedies",
      "description": "R.J. travels to Georgia for his parents' 50th anniversary. But after pompously flaunting his Hollywood lifestyle, he must examine what he's become."
    },
    {
      "show_id": "s184",
      "type": "Movie",
      "title": "In the Line of Fire",
      "director": "Wolfgang Petersen",
      "cast": "Clint Eastwood, John Malkovich, Rene Russo, Dylan McDermott, Gary Cole, Fred Thompson, John Mahoney, Gregory Alan Williams, Jim Curley, Sally Hughes",
      "country": "United States",
      "date_added": "August 31, 2021",
      "release_year": 1993,
      "rating": "R",
      "duration": "129 min",
      "listed_in": "Action & Adventure, Classic Movies",
      "description": "A twisted yet ingenious killer torments a veteran Secret Service agent who's haunted by his failure years ago to save President John F. Kennedy."
    }]